# Generated by Django 4.2.3 on 2026-01-30 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('altitude', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('velocity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'telemetry entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
